[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "equestrian-management"
version = "0.1.0"
description = "Equestrian Management System"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]